[project]
name = "k-radio-recorder"
version = "0.1.0"
description = "대한민국 주요 라디오 방송 스트림을 CLI에서 녹음하는 Python 도구"
authors = [{ name = "comfuture" }]
requires-python = ">=3.8"
dependencies = ["argparse", "httpx>=0.28.1"]

[tool.uv]
# uv 관련 추가 설정이 필요한 경우 여기에 작성
